/**
 * BWF's official category taxonomy (client-supplied) — the curated set
 * offered to a brand-new applicant on /apply. Deliberately separate from
 * the full Category table, which also holds the precise (sometimes
 * one-off) category text printed on each existing member's actual roster
 * sheet — those stay exactly as they are on the member's own record, they
 * just aren't generic options a new applicant should be offered.
 *
 * prisma/seed-apply-categories.ts creates these as active Category rows;
 * this same list is what src/app/(public)/apply/page.tsx filters to.
 */
export const APPLY_CATEGORY_NAMES = [
  "Air Conditioner Sales / Service",
  "Aluminium Fabricator",
  "Architect - 1",
  "Architect - 2",
  "Architect - 3",
  "Bio Septic Tank",
  "Borewell",
  "Bricks (Red, Fly Ash, Porotherm)",
  "Builder - 1",
  "Builder - 2",
  "Builder - 3",
  "Building Materials (M-Sand, Blue Metal)",
  "CCTV",
  "Cement",
  "Civil Contractors 1",
  "Civil Contractors 2",
  "Civil Contractors 3",
  "Computer Peripherals Supplies & Services",
  "Concrete Blocks",
  "Paver Block, Solid Block",
  "Curtains & Blind",
  "Digital Marketing",
  "Document Writer",
  "Earth Movers",
  "Electrical Contractor",
  "Electrical Supplier",
  "Facility Management / Property Management",
  "Facade/Cladding/Glazing Contractors",
  "False Ceiling",
  "Fencing Contractor",
  "Furniture MFRS / Dealers",
  "Generator",
  "Glass & Mirror",
  "Granites / Marble",
  "Gypsum Plaster",
  "Hard Tools (Offshore/Marine/Heavy Lift)",
  "Hardwares and Tools",
  "Home Loans",
  "Home Theatre",
  "Interior Decorators Residential",
  "Landscaping",
  "Lights Fittings Dealers",
  "Lift",
  "Mosquito Net Fabricators",
  "MS Grill Fabricators",
  "Office Equipments and Supplies",
  "Paint Suppliers",
  "Painting Contractor",
  "Pre-Engineered Buildings",
  "Pest Control",
  "Pile Foundation",
  "Plan Approval",
  "Surveyor",
  "Plumbing Contractor",
  "Plywood / Laminates",
  "Project Management Consultant (PMC)",
  "Promoters (Layout Developers)",
  "PVC Fabricators / Suppliers",
  "Ready Mix Concrete (RMC)",
  "Real Estate Consultant",
  "Renovation Contractor",
  "RO & Water Treatment Plant",
  "Roofing Materials",
  "Safety Items",
  "Shower Cubicles / Partitions Suppliers",
  "Shuttering Work",
  "Solar Energy Products",
  "SS Pipes & Tubes Mfrs, Fabricators",
  "Steel & TMT Bars",
  "Steel Gates Manufacturers / Dealers",
  "Structural Engineer",
  "Swimming Pool",
  "Tiles, Bathroom Fittings, Plumbing Materials",
  "Timber - Doors and Windows",
  "Toughened Glass (OTS Bathroom)",
  "UPS, Inverter, Battery",
  "UPVC Doors & Windows",
  "Wall Designers (Special Paintings)",
  "Wall Papers",
  "Water Proofing & Construction Chemicals",
  "Waterproofing Contractor",
  "Paint Manufacturers",
  "Signage Metal Sign Board",
  "Fire and Safety Equipments",
  "Epoxy flooring and PU flooring",
  "Photocopiers and Printers",
  "Container Office/ Home Fabricator",
  "Fiber For Construction and Civil Work",
  "Elevation, Plan, Interior Views",
  "Electrical Consultant, Panel board Supplier, GFRB Products",
  "Interior Decorators - Commercial",
  "Interior Decorators - Corporate",
  "M Sand Manufacturers",
  "Corporate Gift",
  "Home Automation",
  "MEP Consultant",
  "Photography & Event",
  "Gate Automation",
  "Interior - residential (modular)",
  "Misc Construction Materials",
  "Insurance & Investment Advisor",
  "CHINA BUSINESS TRIP & GLOBAL SHIPPING",
  "Promoters - Legal & Approval consultant",
  "Soil Testing",
  "Advocate & Tax Attorney",
  "Logistics services",
  "PWD Contractor",
  "Interior Exterior Products",
  "CNC Cutting",
] as const;
